#!/usr/bin/env python
# -*- coding:UTF-8 -*-

from random import choice

mot=raw_input("votre mot?")
mot.lower()
print mot

voyelles=("a","e","i","o","u","y")
consonnes=("b","c","d","f","g","h","j","k","l","m","n","p","q","r","s","t","v","w","x","z")

if mot[len(mot)-2:len(mot)]=="er":
    mot=mot[0:len(mot)-2]+"é"
elif mot[len(mot)-2:len(mot)]=="et":
    mot=mot[0:len(mot)-2]+"é"

if mot[0] in voyelles:
    pick=choice(consonnes)
    mot_2=mot+pick
elif mot[0]=="q" and mot[1]=="u":
    mot_2=mot[2:]+"qu"
elif mot[0] in consonnes and mot[1] in consonnes:
    mot_2=mot[2:]+mot[0]+mot[1]
elif mot[0] in consonnes:
    mot_2=mot[1:]+mot[0]

print "traduction: "+" l"+mot_2+"èm"
